export interface GeorideAPIAuthToken {
    id: number,
    email: string,
    isAdmin: boolean,
    authToken: string,
    updatedAt: Date,
}

export interface GeorideAPITrip {
    id: number | null,
    trackerId: number,
    averageSpeed: number,
    maxSpeed: number,
    distance: number,
    duration: number,
    startAddress: string,
    niceStartAddress: string | null,
    startLat: number,
    startLon: number,
    endAddress: string,
    niceEndAddress: string | null,
    endLat: number,
    endLon: number,
    startTime: string,
    endTime: string,
    staticImage: string,
    maxAngle: number,
    maxLeftAngle: number,
    maxRightAngle: number,
    averageAngle: number,
  }